[globals]
AUTOLOAD=app/|app/controllers/|app/models/|app/utils/
UI=app/views/
timezone=America/New York

CACHE=TRUE

DEBUG=3
;0 : suppresses logs of the stack trace.
;1 : logs files & lines.
;2 : logs classes & functions as well.
;3 : logs detailed infos of the objects as well

; site specific variables
LOCALES="dict/"
;sitelang="sp"
sitelang="en"
;LANGUAGE = "en"

xai_api_key = "YOUR_XAI_API_KEY_HERE"
openai_api_key = "YOUR_OPENAI_API_KEY_HERE"
TO_ANALYZE_TABLE = task
TO_ANALYZE_FIELD = task_type
TO_ANALYZE_FILTER_FIELD = task_date


;automatically logout after this many seconds of inactivity
auto_logout=42000

;Default Values or General Config Variables
condicion_cita = ""
approot = "tas2023.online/"

;$this->f3->get('FREE["limits"]["projects"]');
[FREE.limits]
projects = 4
tasks = 100
actions = 20
images = 6

[PROFESSIONAL.limits]
projects = 40
tasks = 300
actions = 40
images = 40

[ENTERPRISE.limits]
projects = 80
tasks = 600
actions = 80
images = 80