[globals]
AUTOLOAD=app/|app/controllers/|app/models/|app/utils/
UI=app/views/
timezone=America/New York

CACHE=TRUE

DEBUG=3
;0 : suppresses logs of the stack trace.
;1 : logs files & lines.
;2 : logs classes & functions as well.
;3 : logs detailed infos of the objects as well

; site specific variables
LOCALES="dict/"
;sitelang="sp"
sitelang="en"
;LANGUAGE = "en"

xai_api_key = "YOUR_XAI_API_KEY_HERE"
openai_api_key = "YOUR_OPENAI_API_KEY_HERE"
TO_ANALYZE_TABLE = task
TO_ANALYZE_FIELD = task_type
TO_ANALYZE_FILTER_FIELD = task_date
TO_ANALYZE_FILTER_VALUE = 24/05/2024
TO_ANALYZE_QUERY = "SELECT ppt.*, t.* FROM project_person_task ppt JOIN task t ON ppt.task_num = t.task_num WHERE ppt.entity_num = :project_id AND ppt.type_entity = 'project'"
TO_ANALYZE_QUERY2 = "SELECT t.task_num, t.project_num, t.username, t.task_title, t.task_date, t.task_status, t.task_desc, n.note_num, n.note_title, n.note_status, n.note_content, n.note_createdat, n.note_updatedat FROM task t LEFT JOIN note n ON t.task_num = n.task_num JOIN project_person_task ppt ON t.task_num = ppt.task_num JOIN project p ON ppt.entity_num = p.project_id AND ppt.type_entity = 'project' WHERE p.project_id = :project_id AND MONTH(STR_TO_DATE(t.task_date, '%d/%m/%Y')) = 12 AND YEAR(STR_TO_DATE(t.task_date, '%d/%m/%Y')) = 2025"
TO_ANALYZE_PARAMS = "{\"project_id\": 32}"

;automatically logout after this many seconds of inactivity
auto_logout=42000

;database credentials
;db_dns=mysql:host=localhost;port=3306;dbname=u991737198_tas2023;
;db_dns_short=mysql:host=localhost;port=3306;
;db_name=u991737198_tas2023
;db_user=u991737198_admin
;db_pass=Sk8-board

;mail settings
from_email=admin@tas2023.online
smtp_host="smtp.titan.email"
smtp_port="587"
smtp_scheme="STARTTLS"
smtp_user="admin@tas2023.online"
smtp_pw="Sk8-board"

;Default Values or General Config Variables
condicion_cita = ""
approot = "tas2023.online/"

;$this->f3->get('FREE["limits"]["projects"]');
[FREE.limits]
projects = 4
tasks = 100
actions = 20
images = 6

[PROFESSIONAL.limits]
projects = 40
tasks = 300
actions = 40
images = 40

[ENTERPRISE.limits]
projects = 80
tasks = 600
actions = 80
images = 80