[routes]
GET|POST /=UserController->login
GET|POST /index=UserController->login
GET /home=PageController->homepage
GET /notification/fetch=NotificationController->fetchNotifications
GET /notification/fetch1=NotificationController->fetch
POST /notification/mark_as_read=NotificationController->markAsRead
POST /notification/update_status/@notificationId=NotificationController->toggleStatus

;USER
GET|POST /login=UserController->login
GET|POST /logout=UserController->logout
GET|POST /lostpassword=UserController->lostpassword
GET|POST /pw_reset=UserController->pw_reset
GET|POST /register=UserController->create
GET /@Target=UserController->@Target
GET|POST /sendactivationmail=UserController->sendactivationmail
GET /confirm_registration=UserController->confirm_registration
GET /registration_complete=UserController->success
GET|POST /user/update=UserController->edit_registration
GET|POST /user/profile=UserController->profile
POST /user/loadphoto=UserController->loadphoto
GET /page/homepage=PageController->homepage
GET /page/prueba=PageController->responsinput
GET /user/listuser=UserController->list_user
GET /user/listuser/@ProjectId=UserController->list_user
GET /user/listuserq/@q=UserController->list_user
GET /user/find/@UserId/@ProjectId=UserController->list_user
GET /user/edit/@UserId/@ProjectId=ProjectController->update
POST /user/invite=UserController->invite
POST /user/updategrants=UserController->updategrants
POST /user/saveFcmToken=UserController->saveFcmToken
GET /user/notifications=UserController->notifications
POST /user/deletenotif=UserController->deletenotif

;TASK
POST /task/loadimage=TaskController->loadimage
POST /task/deleteimage = TaskController->deleteImage
GET|POST /task/listtask=TaskController->list_task
GET|POST /task/listtasks=TaskController->list_tasks
GET /task/listtask/@TaskDate=TaskController->list_task
GET /task/listtask/@TaskDate/@msg/@alert=TaskController->list_task
GET /task/listtask/@TaskDate/@msg=TaskController->list_task
GET /success/@message=TaskController->list_task
GET /registertask=TaskController->newtask
GET|POST /newtask=TaskController->create
GET|POST /task/tskdelete/@TaskNum/@EntityNum/@TypeEntity/@MyView=TaskController->delete
GET|POST /task/taskdelete/@TaskNum/@EntityNum/@TypeEntity=TaskController->taskdelete
GET|POST /task/delete/@TaskDate/@EntityNum/@TaskNum/@TypeEntity=TaskController->list_task
GET /task/persontask/@PersonNum=TaskController->persontask
GET|POST /task/edit/@EntityNum/@TaskNum/@TypeEntity=TaskController->edittask
POST /task/edit=TaskController->edittask
GET /task/view/@EntityNum/@TaskNum/@TypeEntity=TaskController->viewtask
GET /task/summary=TaskController->taskSummary
GET /task/taskData=TaskController->fetchTaskData
GET /task/taskDistribution = TaskController->fetchTaskDistribution
GET /task/teamProductivity = TaskController->fetchTeamProductivity
GET /task/userNotesCount = TaskController->fetchUserNotesCount
POST /task/deleteimage=TaskController->deleteimage

;NOTE
GET|POST /note/listnote=NoteController->list_note
GET /note/listnote/@PersonNum/@TaskNum=NoteController->list_note
GET /success/@message=NoteController->list_note
GET /registerconsulta=ConsultaController->nuevaconsulta
GET|POST /note/create=TaskController->createnote
GET|POST /note/edit=TaskController->editnote
GET /note/find/@NoteNum/@EntityNum/@TaskNum/@TypeEntity=TaskController->edittask
GET|POST /note/delete/@NoteNum/@EntityNum/@TaskNum/@TypeEntity/@Target=TaskController->@Target
GET /generar_pdf/@CodHistoria/@NumCita=ConsultaController->generar_pdf
POST /note/updateStatus=NoteController->updateStatus

;PERSON
;GET|POST /createperson=PersonController->createperson
GET|POST /person/createperson=PersonController->createperson
;GET /registerperson/@PersonNum=PersonController->createperson
GET /person/listperson=PersonController->listperson
GET /person/prueba=PersonController->prueba

;GET /person/listperson/@q=PersonController->listperson

GET /person/update/@person_phone=PersonController->update
POST /person/update=PersonController->update
GET /person/delete/@PersonPhone=PersonController->delete
GET|POST /verifyperson=PersonController->verify
GET /result/@message/@alertType=PersonController->listperson
GET /successperson/@message/@token/@alertType=PersonController->listperson
;la proxima linea es la que esta asociada al modal crear cita desde lista de pacientes
GET /person/find/@PersonPhone=PersonController->listperson
GET /person/addperson/@PersonPhone=PersonController->addperson

;PROJECT
GET|POST /project/listproject=ProjectController->listproject
GET|POST /project/createproject=ProjectController->createproject
POST /project/update=ProjectController->update
GET /project/update/@project_id=ProjectController->update
GET /project/update/@UserId/@ProjectId=ProjectController->update
;GET /project/delete/@ProjectId=ProjectController->delete
GET /project/delete/@ProjectId/@Action=ProjectController->listproject
GET /project/find/@ProjectId=ProjectController->listproject
GET /successproject/@message/@token/@alertType=ProjectController->listproject
POST /project/updategrants=ProjectController->updategrants
GET /project/deletepu/@UserId/@ProjectId=ProjectController->deletepu

;ADMIN PAGES
GET /admin/users=AdminController->users
GET|POST /admin/users/new=AdminController->superuser
GET|POST /admin/users/@codusuario=AdminController->show_user
GET /admin/projectbackup=AdminController->projectBackup
GET /admin/backup=AdminController->backupDb
GET /admin/openai=AdminController->openai
;GET /admin/openai=AdminController->chat
GET /admin/analyze=OpenAIController->analyzeData
GET /admin/xanalyze=XAIController->analyzeData
GET /admin/compactusers=AdminController->compactUsers
GET /admin/compacttableForm=AdminController->compactTableForm
GET|POST /admin/compacttable=AdminController->compactTable
GET /admin/updateI18nStrings=AdminController->updateI18nStrings
;POST /admin/openai=ChatController->chat

;GET /admin/openai=OpenAIController->showForm
POST /admin/openai=OpenAIController->handleRequest

;TEST
;GET|POST /paciente/buscar=PacienteController->listpaciente
GET /task/pruebamodal=TaskController->pruebamodal
GET|POST /checkUserExists=UserController->checkUserExists
GET|POST /checkPersonExists=PersonController->checkPersonExists